const app=document.getElementById('app'), modalRoot=document.getElementById('modal-root'), toastEl=document.getElementById('toast');
const models=[
 {id:'seal',name:'BYD SEAL',type:'Electric Sedan',price:'₦35,000,000',range:'Up to 650 km*',battery:'82.5 kWh',accel:'3.8 s',tag:'Electric Sedan',desc:'A performance-focused electric sedan with sleek Ocean-inspired design, advanced Blade Battery technology and intelligent driving features.',image:'assets/seal-hd.jpg'},
 {id:'atto3',name:'BYD ATTO 3',type:'Electric SUV',price:'₦28,500,000',range:'Up to 480 km*',battery:'60.48 kWh',accel:'7.3 s',tag:'Electric SUV',desc:'A confident electric SUV designed for everyday life with smart technology, practical space and a refined drive.',image:'assets/atto3-hd.jpg'},
 {id:'han',name:'BYD HAN',type:'Electric Sedan',price:'₦42,000,000',range:'Executive EV',battery:'85.4 kWh',accel:'3.9 s',tag:'Premium Electric Sedan',desc:'A flagship electric sedan combining performance, luxury, advanced safety and premium technology.',image:'assets/han-hd.jpg'},
 {id:'dolphin',name:'BYD DOLPHIN',type:'Electric Hatchback',price:'₦22,500,000',range:'Urban EV',battery:'44.9 kWh',accel:'7.0 s',tag:'Urban Electric',desc:'Compact, intelligent and efficient — built for modern city driving with a playful design and practical range.',image:'assets/dolphin-hd.jpg'},
 {id:'tang',name:'BYD TANG',type:'Electric SUV',price:'₦38,000,000',range:'Premium SUV',battery:'108.8 kWh',accel:'4.6 s',tag:'Premium Electric SUV',desc:'A spacious performance SUV with all-wheel drive, premium comfort and strong electric performance.',image:'assets/tang-hd.jpg'},
 {id:'seal-u-dmi',name:'BYD SEAL U DM-i',type:'Hybrid SUV',price:'₦33,000,000',range:'Super Hybrid',battery:'18.3 kWh',accel:'—',tag:'Plug-in Hybrid SUV',desc:'A versatile plug-in hybrid SUV combining EV-first driving with the flexibility of BYD Super Hybrid DM-i technology.',image:'assets/seal-udmi-hd.jpg'}
];
const plans=[['Bronze','Free','Basic Support','Service Reminders','Member Discounts','Company Updates'],['Silver','₦60,000 / year','Everything in Bronze','Regular Diagnostics','Priority Health Check','Preventive Maintenance'],['Gold','₦120,000 / year','Everything in Silver','Special Issue Coverage','Repair Support','Priority Service'],['Platinum','₦200,000 / year','Everything in Gold','All Repairs Coverage','Full Maintenance Coverage','Priority Booking','24/7 Roadside Assistance']];
function carSVG(m,large=false){
 return `<div class="real-car-wrap ${large?'hero-real-car':''}">
   <div class="car-light-sweep"></div>
   <img class="real-car-image" src="${m.image}" alt="${m.name}" loading="${large?'eager':'lazy'}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">
   <div class="image-fallback"><strong>${m.name}</strong><span>BYD vehicle image</span></div>
   <span class="car-floor-glow"></span>
 </div>`
}
function header(active='home'){return `<header class="topbar olzim-topbar"><div class="container nav"><a class="olzim-logo nav-logo" href="#/"><span class="olzim-mark">⚡</span><span>OLZIM AUTOS<small>Drive the Future</small></span></a><nav class="navlinks"><a class="${active==='home'?'active':''}" href="#/">Home</a><a class="${active==='vehicles'?'active':''}" href="#/vehicles">Vehicles</a><a class="${active==='membership'?'active':''}" href="#/membership">Membership</a><a href="#/about">Company</a><a href="#/contact">Contact Us</a></nav><div class="nav-actions"><button class="iconbtn" onclick="notify('Search is ready')">⌕</button><button class="iconbtn" onclick="location.hash='#/login'">♙</button>${localStorage.getItem('bydUser')?`<div class="avatar">JD</div>`:`<button class="btn btn-primary nav-register" onclick="location.hash='#/register'">Register</button>`}</div></div></header>`}
function footer(){return `<footer class="footer"><div class="container footer-grid"><div><div class="olzim-logo"><span class="olzim-mark">⚡</span><span>OLZIM AUTOS<small>Drive the Future</small></span></div><p class="footer-copy">Premium electric and hybrid vehicles, professional customer care, test drives and ownership support.</p></div><div><h4>Vehicles</h4><a href="#/vehicles">All Vehicles</a><a href="#/vehicles">Electric Cars</a><a href="#/vehicles">Hybrid Cars</a><a href="#/vehicles">SUVs</a></div><div><h4>Ownership</h4><a href="#/membership">Membership</a><a href="#/dashboard">My Account</a><a href="#/appointments">Service</a><a href="#/support">Support</a></div><div><h4>Company</h4><a href="#/about">About Olzim Autos</a><a href="#/contact">Contact Us</a><a href="#/contact">Request a Quote</a></div></div><div class="container footer-bottom"><span>© 2026 OLZIM AUTOS · BYD Customer Experience</span><span>Prices shown are illustrative and subject to dealer confirmation.</span></div></footer>`}
function home(){return `${header('home')}<main>
<section class="olzim-hero container"><div class="hero-panel"><div class="hero-copy-pro"><div class="hero-kicker-pro"><span></span> ELECTRIC MOBILITY · NIGERIA</div><h1>Drive the Future.<br><em>Drive OLZIM.</em></h1><p>Discover premium BYD electric and hybrid vehicles with transparent pricing, test drives, membership benefits and after-sales support.</p><div class="hero-actions"><button class="btn btn-primary btn-lg" onclick="location.hash='#/vehicles'">Explore Vehicles <b>→</b></button><button class="btn btn-light btn-lg" onclick="location.hash='#/membership'">View Membership</button></div><div class="hero-mini-stats"><div><b>100%</b><span>Electric options</span></div><div><b>650km*</b><span>Max listed range</span></div><div><b>24/7</b><span>Owner support</span></div></div></div><div class="hero-visual"><div class="hero-gridlines"></div><div class="hero-orb orb-a"></div><div class="hero-orb orb-b"></div><div class="speed-lines"></div><div class="hero-car-stage"><img src="assets/hero-car-hd.jpg" alt="BYD SEAL electric sedan"></div><div class="hero-scroll-cue"><span></span>SCROLL TO EXPLORE</div></div></div></section>
<section class="benefits container"><div class="benefitbar premium-benefits"><div class="benefit"><div class="ico">◉</div><div><strong>Blade Battery</strong><span>Advanced safety</span></div></div><div class="benefit"><div class="ico">ϟ</div><div><strong>Fast Charging</strong><span>More time driving</span></div></div><div class="benefit"><div class="ico">◇</div><div><strong>Smart Technology</strong><span>Connected driving</span></div></div><div class="benefit"><div class="ico">♕</div><div><strong>Olzim Membership</strong><span>Premium ownership</span></div></div></div></section>
<section class="section container vehicle-showcase"><div class="section-head"><div><div class="eyebrow">OUR LINEUP</div><h2>Find your next BYD</h2><p>Real BYD models, cinematic previews and quick access to specifications.</p></div><a class="link" href="#/vehicles">View all vehicles →</a></div><div class="category-pills"><button class="active">All Vehicles</button><button>Electric Cars</button><button>Hybrid Cars</button><button>SUV</button><button>Sedan</button><button>Hatchback</button></div><div class="cards six-cards">${models.map(vehicleCard).join('')}</div></section>
<section class="ownership container"><div class="ownership-left"><div class="eyebrow">OWNERSHIP, REIMAGINED</div><h2>More than a car.<br><span>A complete experience.</span></h2><p>From your first test drive to servicing and membership, OLZIM AUTOS gives you one place to manage the journey.</p><div class="ownership-points"><div><b>01</b><span>Book a test drive</span></div><div><b>02</b><span>Request a quote</span></div><div><b>03</b><span>Manage servicing</span></div></div><button class="btn btn-accent btn-lg" onclick="location.hash='#/register'">Create My Account</button></div><div class="dashboard-preview"><div class="dash-preview-head"><span>OLZIM AUTOS</span><b>John Doe</b></div><div class="dash-preview-body"><aside><b>◈</b><span>Dashboard</span><span>My Profile</span><span>My Vehicles</span><span>Membership</span><span>Service History</span><span>Appointments</span></aside><div class="preview-content"><div class="welcome-box"><small>WELCOME BACK</small><h3>John, your BYD is ready.</h3><p>Everything you need for your ownership journey.</p></div><div class="preview-grid"><div class="preview-car"><img src="assets/dashboard-car-hd.jpg" alt="BYD SEAL"><div><b>BYD SEAL</b><span>Electric Sedan</span><strong>₦35,000,000</strong></div></div><div class="membership-preview"><span>MEMBERSHIP LEVEL</span><b>GOLD</b><small>Priority service · Member discounts</small></div></div><div class="preview-stats"><div><b>25 days</b><span>Next service</span></div><div><b>3</b><span>Total services</span></div><div><b>1</b><span>Appointment</span></div></div></div></div></div></section>
<section class="section container"><div class="section-head"><div><div class="eyebrow">MEMBERSHIP</div><h2>Choose your level</h2><p>Premium support designed around your vehicle.</p></div><a class="link" href="#/membership">Compare plans →</a></div><div class="membership-grid home-memberships">${plans.map((p,i)=>`<div class="plan ${i===2?'featured-plan':''}"><div class="medal">${['◆','◇','✦','♕'][i]}</div><h3>${p[0]}</h3><div class="plan-price">${p[1]}</div><ul>${p.slice(2,6).map(x=>`<li>${x}</li>`).join('')}</ul><button class="btn ${i===2?'btn-accent':'btn-outline'} full" onclick="choosePlan('${p[0]}')">${i===0?'Current Plan':'Choose Plan'}</button></div>`).join('')}</div></section>
<section class="why-olzim container"><div><div class="eyebrow">WHY OLZIM AUTOS</div><h2>Confidence at every turn.</h2><p>Premium vehicles deserve premium support. Explore technology, service and ownership benefits built into the OLZIM experience.</p></div><div class="why-grid"><div class="why-item"><div class="ico">◉</div><strong>Long Range</strong><span>Efficient electric driving for city and highway journeys.</span></div><div class="why-item"><div class="ico">ϟ</div><strong>Fast Charging</strong><span>Modern charging technology to reduce downtime.</span></div><div class="why-item"><div class="ico">⌁</div><strong>Smart Technology</strong><span>Connected features for a safer, smarter drive.</span></div><div class="why-item"><div class="ico">✧</div><strong>After-Sales Care</strong><span>Service reminders, support and ownership assistance.</span></div></div></section>
<section class="cta container"><div><div class="eyebrow">READY TO DRIVE?</div><h2>Meet your next BYD.</h2><p>Book a test drive or request a personalised quotation from OLZIM AUTOS.</p></div><div><button class="btn btn-accent btn-lg" onclick="openTestDrive('BYD SEAL')">Book a Test Drive</button><button class="btn btn-light btn-lg" onclick="openQuote('BYD SEAL')">Request a Quote</button></div></section>
</main>${footer()}`}
function vehicleCard(m){return `<article class="vehicle-card premium-card fleet-card reveal-card" onclick="location.hash='#/vehicle/${m.id}'"><div class="vehicle-image fleet-image">${carSVG(m)}</div><div class="vehicle-info fleet-info"><div class="vehicle-label"><i></i>${m.tag}</div><div class="fleet-title-row"><div><h3>${m.name}</h3><div class="type">${m.type}</div></div><span class="arrow">↗</span></div><div class="fleet-specs"><span><small>RANGE</small><b>${m.range.replace('Up to ','')}</b></span><span><small>BATTERY</small><b>${m.battery}</b></span><span><small>0–100 KM/H</small><b>${m.accel}</b></span></div><div class="fleet-cta">VIEW MODEL <span>→</span></div></div></article>`}
function vehicles(){return `${header('vehicles')}<main class="page container"><div class="page-title"><div class="eyebrow">OLZIM AUTOS · BYD RANGE</div><h1>Our Vehicles</h1><p>Explore electric and hybrid BYD models with cinematic previews and key specifications.</p></div><div class="filters"><button class="filter active" data-filter="all" onclick="filterVehicles('all',this)">All Vehicles</button><button class="filter" data-filter="Electric" onclick="filterVehicles('Electric',this)">Electric Cars</button><button class="filter" data-filter="Hybrid" onclick="filterVehicles('Hybrid',this)">Hybrid Cars</button><button class="filter" data-filter="SUV" onclick="filterVehicles('SUV',this)">SUV</button><button class="filter" data-filter="Sedan" onclick="filterVehicles('Sedan',this)">Sedan</button><button class="filter" data-filter="Hatchback" onclick="filterVehicles('Hatchback',this)">Hatchback</button></div><div id="vehicle-grid" class="vehicles-grid">${models.map(vehicleCard).join('')}</div><div class="dark-panel sales-banner"><div><div class="eyebrow">PERSONALISED ASSISTANCE</div><h2>Can't find what you're looking for?</h2><p>Talk to OLZIM AUTOS about availability, financing, import options and test drives.</p></div><button class="btn btn-accent" onclick="openContact()">Contact Sales</button></div></main>${footer()}`}
function filterVehicles(filter,el){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));el.classList.add('active');let list=models;if(filter!=='all') list=models.filter(m=>m.type.includes(filter)||(filter==='SUV'&&m.tag.includes('SUV'))||(filter==='Sedan'&&m.type.includes('Sedan'))||(filter==='Hatchback'&&m.type.includes('Hatchback')));document.getElementById('vehicle-grid').innerHTML=list.map(vehicleCard).join('')}
function membership(){return `${header('membership')}<main class="page container"><div class="page-title"><div class="eyebrow">Member benefits</div><h1>Membership Plans</h1><p>Choose the plan that fits your needs. You can change plans anytime in this demo.</p></div><div class="membership-grid">${plans.map((p,i)=>`<div class="plan ${i===0?'current':''}"><div class="medal">${['◆','◇','✦','♕'][i]}</div><h3>${p[0]}</h3><div class="plan-price">${p[1]}</div><ul>${p.slice(2).map(x=>`<li>${x}</li>`).join('')}</ul><button class="btn ${i===0?'btn-outline':'btn-primary'} full" onclick="choosePlan('${p[0]}')">${i===0?'Current Plan':'Choose Plan'}</button></div>`).join('')}</div><section class="section" style="padding-bottom:20px"><div class="panel" style="padding:25px"><h3 style="margin:0 0 16px;font-size:14px">Compare Plans</h3><div class="list-row"><b>Basic Support</b><span>✓ &nbsp; ✓ &nbsp; ✓ &nbsp; ✓</span></div><div class="list-row"><b>Service Reminders</b><span>✓ &nbsp; ✓ &nbsp; ✓ &nbsp; ✓</span></div><div class="list-row"><b>Priority Booking</b><span>— &nbsp; — &nbsp; ✓ &nbsp; ✓</span></div><div class="list-row"><b>24/7 Roadside Assistance</b><span>— &nbsp; — &nbsp; — &nbsp; ✓</span></div></div></section></main>${footer()}`}
function choosePlan(name){if(!localStorage.getItem('bydUser')){location.hash='#/register';return}notify(`${name} plan selected — demo confirmation complete`)}
function vehicleDetail(id){const m=models.find(x=>x.id===id)||models[0];return `${header('vehicles')}<main class="page container"><div style="font-size:10px;color:var(--muted);margin-bottom:15px;cursor:pointer" onclick="location.hash='#/vehicles'">← Back to Vehicles</div><div class="detail"><div class="detail-photo">${carSVG(m,true)}</div><div class="detail-copy"><div class="eyebrow">${m.tag}</div><h1>${m.name}</h1><div class="sub">${m.type}</div><div class="detail-price">${m.price}</div><div class="specs"><div class="spec"><small>Range</small><strong>${m.range}</strong></div><div class="spec"><small>Battery Capacity</small><strong>${m.battery}</strong></div><div class="spec"><small>0–100 km/h</small><strong>${m.accel}</strong></div></div><p style="font-size:12px;line-height:1.8;color:var(--muted)">${m.desc}</p><div style="display:flex;gap:8px;margin-top:20px"><button class="btn btn-primary" onclick="openTestDrive('${m.name}')">Book a Test Drive</button><button class="btn btn-outline" onclick="openQuote('${m.name}')">Request Quote</button></div><div class="tabs"><div class="tab active">Overview</div><div class="tab">Specifications</div><div class="tab">How It Works</div><div class="tab">Gallery</div></div></div></div><div class="dark-panel" style="margin-top:24px"><h2>About BYD</h2><p>Innovative electric mobility built around battery technology, smart platforms and a customer-first ownership experience.</p></div></main>${footer()}`}
function about(){return `${header()}<main class="page container"><div class="page-title"><div class="eyebrow">About the concept</div><h1>About BYD EV</h1><p>Technology, innovation and sustainable mobility brought into one clean customer experience.</p></div><div class="detail" style="align-items:stretch"><div class="panel" style="padding:30px"><h2 style="font-size:25px">Technology that moves you</h2><p style="font-size:12px;line-height:1.9;color:var(--muted)">This demo portal is designed around the structure in your reference: a premium public website, vehicle catalogue, membership plans and a logged-in owner dashboard.</p><p style="font-size:12px;line-height:1.9;color:var(--muted)">The vehicle catalogue now uses real BYD model names and real vehicle photography from Wikimedia Commons. Model specifications should be verified against the final Nigerian market configuration before publishing commercial claims or prices.</p><button class="btn btn-primary" onclick="location.hash='#/vehicles'">Explore Vehicles</button></div><div class="detail-photo" style="min-height:300px">${carSVG(models[5])}</div></div></main>${footer()}`}
function contact(){return `${header()}<main class="page container"><div class="page-title"><div class="eyebrow">We're here to help</div><h1>Contact Us</h1><p>Sales, service, membership or general enquiries.</p></div><div class="detail"><div class="panel" style="padding:25px"><h3>Contact Sales</h3><div class="field"><label>Name</label><input id="cname" placeholder="Your name"></div><div class="field"><label>Email</label><input id="cemail" type="email" placeholder="you@example.com"></div><div class="field"><label>Message</label><textarea id="cmsg" rows="5" placeholder="How can we help?"></textarea></div><button class="btn btn-primary" onclick="sendContact()">Send Enquiry</button></div><div class="panel" style="padding:25px"><h3>Customer Care</h3><div class="list-row"><span>Sales</span><b>+234 800 BYD DEMO</b></div><div class="list-row"><span>Email</span><b>hello@bydev.demo</b></div><div class="list-row"><span>Hours</span><b>Mon–Sat · 8:00–18:00</b></div><div class="dark-panel" style="margin-top:20px"><h2>Need a test drive?</h2><p>Choose a model and book a slot.</p><button class="btn btn-primary" onclick="openTestDrive('BYD SEAL')">Book Test Drive</button></div></div></div></main>${footer()}`}
function auth(mode){let register=mode==='register';return `<div class="auth-wrap"><div class="auth-card"><div class="brand" style="margin-bottom:25px"><span class="brand-mark"></span>BYD <small>NIGERIA</small></div><h1>${register?'Create account':'Welcome back'}</h1><p>${register?'Join BYD EV membership and manage your vehicle online.':'Sign in to your owner dashboard.'}</p>${register?`<div class="field"><label>Full Name</label><input id="authName" placeholder="John Doe"></div>`:''}<div class="field"><label>Email</label><input id="authEmail" type="email" placeholder="john@example.com"></div><div class="field"><label>Password</label><input id="authPass" type="password" placeholder="••••••••"></div><button class="btn btn-primary full" onclick="submitAuth('${mode}')">${register?'Create Account':'Sign In'}</button><div class="auth-switch">${register?'Already have an account?':'New to BYD EV?'} <span onclick="location.hash='#/${register?'login':'register'}'">${register?'Sign in':'Create account'}</span></div><div class="auth-switch" style="margin-top:20px"><span onclick="location.hash='#/'">← Back to website</span></div></div></div>`}
function submitAuth(mode){const email=document.getElementById('authEmail').value.trim();const pass=document.getElementById('authPass').value;if(!email||!pass){notify('Please complete the required fields');return}const name=mode==='register'?(document.getElementById('authName').value.trim()||'John Doe'):'John Doe';localStorage.setItem('bydUser',JSON.stringify({name,email}));notify(mode==='register'?'Account created successfully':'Signed in successfully');setTimeout(()=>location.hash='#/dashboard',350)}
function dashboard(section='dashboard'){let u=JSON.parse(localStorage.getItem('bydUser')||'{}');const title={dashboard:'Dashboard',profile:'My Profile',vehicles:'My Vehicles',membership:'Membership',history:'Service History',appointments:'Appointments',payments:'Payments',support:'Support',settings:'Settings'}[section]||'Dashboard';return `<div class="dashboard"><aside class="sidebar"><div class="side-brand">BYD <span style="color:#8da1bc">EV</span></div><div class="side-label">Account</div>${[['dashboard','⌂'],['profile','◉'],['vehicles','▣'],['membership','♕'],['history','↻'],['appointments','◷'],['payments','₦'],['support','?'],['settings','⚙']].map(([x,ic])=>`<a class="side-link ${section===x?'active':''}" href="#/${x==='dashboard'?'dashboard':x}"><span>${ic}</span>${x[0].toUpperCase()+x.slice(1)}</a>`).join('')}<div style="margin-top:25px"><a class="side-link" onclick="logout()"><span>↪</span>Logout</a></div></aside><main class="dash-main"><div class="welcome"><div><h1>${title}</h1><p>${section==='dashboard'?`Welcome back, ${u.name||'John'}! Here's what's happening with your membership.`:'Manage your BYD EV account.'}</p></div><div class="level"><span>Membership Level</span><strong>🥉 Bronze</strong><small style="display:block;margin-top:4px;color:#8b96a5">Member since May 2026</small></div></div>${section==='dashboard'?dashboardHome():dashboardSection(section)}</main></div>`}
function dashboardHome(){return `<div class="dash-grid"><div><div class="dash-card"><h3>My Vehicle</h3><div class="vehicle-mini"><div class="mini-img">${carSVG(models[1])}</div><div><strong>BYD SEAL</strong><small>Electric Sedan</small><small>VIN: OLZIM-DEMO-48221</small><button class="btn btn-primary" style="margin-top:9px;padding:8px 11px" onclick="location.hash='#/vehicles'">View Vehicle Details</button></div></div></div><div class="dash-stats"><div class="stat"><small>Next Service</small><strong>25 days</strong></div><div class="stat"><small>Total Services</small><strong>3</strong></div><div class="stat"><small>Active Appointments</small><strong>1</strong></div></div></div><div class="dash-card"><h3>Membership Overview</h3><div class="list-row"><span>Basic Support</span><b>✓</b></div><div class="list-row"><span>Service Reminders</span><b>✓</b></div><div class="list-row"><span>Member Discounts</span><b>✓</b></div><button class="btn btn-primary full" style="margin-top:14px" onclick="location.hash='#/membership'">Upgrade Membership</button></div></div><div class="dash-grid" style="margin-top:16px"><div class="dash-card"><h3>Upcoming Appointment</h3><div class="list-row"><span>Vehicle Health Check</span><b>15 Oct 2026</b></div><div class="list-row"><span>Location</span><b>BYD Service Centre</b></div><button class="btn btn-outline" style="margin-top:12px" onclick="location.hash='#/appointments'">View Appointment</button></div><div class="dash-card"><h3>Quick Actions</h3><button class="btn btn-soft full" style="margin-bottom:8px" onclick="openTestDrive('BYD SEAL')">Book Test Drive</button><button class="btn btn-soft full" onclick="location.hash='#/support'">Contact Support</button></div></div>`}
function dashboardSection(section){const content={profile:`<div class="panel" style="padding:24px"><h3>Personal Information</h3><div class="form-grid"><div class="field"><label>Full Name</label><input value="John Doe"></div><div class="field"><label>Email</label><input value="john@example.com"></div><div class="field"><label>Phone</label><input value="+234 800 000 0000"></div><div class="field"><label>City</label><input value="Abuja"></div></div><button class="btn btn-primary" onclick="notify('Profile changes saved')">Save Changes</button></div>`,vehicles:`<div class="cards">${models.slice(1,3).map(vehicleCard).join('')}</div><button class="btn btn-primary" style="margin-top:18px" onclick="location.hash='#/vehicles'">Add Vehicle</button>`,membership:`${membership().replace(/^.*?<main class="page container">/s,'<div>').replace(/<\/main>.*$/s,'</div>')}`,history:`<div class="panel" style="padding:24px"><h3>Service History</h3>${['Vehicle Health Check','Battery Diagnostic','Software Update'].map((x,i)=>`<div class="list-row"><span>${x}<small style="display:block;color:#9aa5b3;margin-top:4px">${['12 Jun 2026','14 Mar 2026','05 Jan 2026'][i]}</small></span><b>Completed</b></div>`).join('')}</div>`,appointments:`<div class="panel" style="padding:24px"><h3>Appointments</h3><div class="list-row"><span>Vehicle Health Check<br><small>15 Oct 2026 · 10:00 AM</small></span><span class="status">Confirmed</span></div><button class="btn btn-primary" style="margin-top:18px" onclick="openService()">Book Service</button></div>`,payments:`<div class="panel" style="padding:24px"><h3>Payments</h3><div class="list-row"><span>Bronze Membership</span><b>Free</b></div><div class="list-row"><span>Last Service</span><b>₦0.00</b></div><p style="font-size:10px;color:var(--muted)">Demo environment — no real payments are processed.</p></div>`,support:`<div class="panel" style="padding:24px"><h3>Support</h3><p style="font-size:11px;color:var(--muted)">Tell us what you need help with.</p><div class="field"><textarea id="supportMsg" rows="5" placeholder="Describe your issue..."></textarea></div><button class="btn btn-primary" onclick="notify('Support request submitted')">Submit Request</button></div>`,settings:`<div class="panel" style="padding:24px"><h3>Settings</h3>${['Email notifications','Service reminders','Membership updates'].map(x=>`<div class="list-row"><span>${x}</span><input type="checkbox" checked></div>`).join('')}<button class="btn btn-primary" style="margin-top:18px" onclick="notify('Settings saved')">Save Settings</button></div>`};return content[section]||dashboardHome()}
function openModal(title,body){modalRoot.innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close" onclick="closeModal()">×</button></div>${body}</div></div>`}
function closeModal(){modalRoot.innerHTML=''}
function openTestDrive(model){openModal('Book a Test Drive',`<p style="font-size:11px;color:var(--muted)">Request a demo test drive for <b>${model}</b>.</p><div class="form-grid"><div class="field"><label>Full Name</label><input id="tdName" placeholder="Your name"></div><div class="field"><label>Phone</label><input id="tdPhone" placeholder="+234"></div><div class="field"><label>Date</label><input id="tdDate" type="date"></div><div class="field"><label>Preferred Time</label><select id="tdTime"><option>10:00 AM</option><option>12:00 PM</option><option>2:00 PM</option><option>4:00 PM</option></select></div></div><div class="modal-actions"><button class="btn btn-outline" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="confirmTestDrive('${model}')">Submit Request</button></div>`)}
function confirmTestDrive(model){closeModal();notify(`Test drive request for ${model} submitted`)}
function openQuote(model){openModal('Request a Quote',`<p style="font-size:11px;color:var(--muted)">Get a demo quotation for <b>${model}</b>.</p><div class="field"><label>Full Name</label><input id="qname" placeholder="Your name"></div><div class="field"><label>Email</label><input id="qemail" type="email" placeholder="you@example.com"></div><div class="field"><label>Message</label><textarea id="qmsg" rows="4">I would like a quotation for ${model}.</textarea></div><div class="modal-actions"><button class="btn btn-outline" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="closeModal();notify('Quote request submitted')">Request Quote</button></div>`)}
function openService(){openModal('Book a Service',`<div class="field"><label>Service</label><select><option>Vehicle Health Check</option><option>Battery Diagnostic</option><option>Software Update</option></select></div><div class="form-grid"><div class="field"><label>Date</label><input type="date"></div><div class="field"><label>Time</label><input type="time"></div></div><div class="modal-actions"><button class="btn btn-outline" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="closeModal();notify('Service appointment booked')">Book Service</button></div>`)}
function openContact(){location.hash='#/contact'}
function sendContact(){notify('Your enquiry has been sent');document.getElementById('cmsg').value=''}
function logout(){localStorage.removeItem('bydUser');notify('Logged out');setTimeout(()=>location.hash='#/',300)}
function notify(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toastEl.classList.remove('show'),2600)}
function render(){let path=location.hash.replace(/^#\/?/,'')||'';let parts=path.split('/');let view=parts[0];if(view==='')app.innerHTML=home();else if(view==='vehicles')app.innerHTML=vehicles();else if(view==='vehicle')app.innerHTML=vehicleDetail(parts[1]);else if(view==='membership')app.innerHTML=membership();else if(view==='about')app.innerHTML=about();else if(view==='contact')app.innerHTML=contact();else if(view==='login'||view==='register')app.innerHTML=auth(view);else if(['dashboard','profile','history','appointments','payments','support','settings'].includes(view)) {if(!localStorage.getItem('bydUser')){location.hash='#/login';return}app.innerHTML=dashboard(view)}else if(view==='my'||view==='vehicles')app.innerHTML=dashboard(view);else app.innerHTML=home();window.scrollTo(0,0)}
window.addEventListener('hashchange',render);render();

// OLZIM visual motion layer — frontend only; backend/API remains unchanged.
function initOlzimMotion(){
  document.querySelectorAll('.reveal-card,.membership-grid .plan,.why-item,.benefit').forEach((el,i)=>{
    el.classList.add('motion-ready');
    el.style.setProperty('--delay', `${Math.min(i*45,360)}ms`);
  });
  if('IntersectionObserver' in window){
    const io=new IntersectionObserver(entries=>{
      entries.forEach(e=>{ if(e.isIntersecting){e.target.classList.add('motion-in');io.unobserve(e.target)} });
    },{threshold:.08});
    document.querySelectorAll('.motion-ready').forEach(el=>io.observe(el));
  } else document.querySelectorAll('.motion-ready').forEach(el=>el.classList.add('motion-in'));
}
window.addEventListener('hashchange',()=>setTimeout(initOlzimMotion,80));
window.addEventListener('load',()=>setTimeout(initOlzimMotion,120));
