require('dotenv').config();
const fs = require('fs'); const path = require('path');
const express = require('express'); const cors = require('cors'); const helmet = require('helmet');
const rateLimit = require('express-rate-limit'); const bcrypt = require('bcryptjs'); const jwt = require('jsonwebtoken');
const Database = require('better-sqlite3');
const app = express();
const PORT = Number(process.env.PORT || 4000);
const JWT_SECRET = process.env.JWT_SECRET || 'dev-only-change-me';
const dbFile = path.resolve(__dirname, process.env.DB_FILE || './data/byd.sqlite');
fs.mkdirSync(path.dirname(dbFile), { recursive: true });
const db = new Database(dbFile); db.pragma('journal_mode = WAL'); db.pragma('foreign_keys = ON');
db.exec(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8'));
const origins=(process.env.CORS_ORIGIN||'*').split(',').map(s=>s.trim()).filter(Boolean);
app.use(helmet()); app.use(cors({origin:(origin,cb)=>{if(!origin||origins.includes('*')||origins.includes(origin)) return cb(null,true); cb(new Error('CORS blocked'));}}));
app.use(express.json({limit:'1mb'}));
const limiter=rateLimit({windowMs:15*60*1000,max:250,standardHeaders:true,legacyHeaders:false}); app.use('/api',limiter);
const authLimiter=rateLimit({windowMs:15*60*1000,max:30,message:{error:'Too many authentication attempts. Try again later.'}}); app.use('/api/auth',authLimiter);
const clean=s=>String(s??'').trim(); const email=s=>clean(s).toLowerCase();
function tokenFor(u){return jwt.sign({sub:u.id,role:u.role,email:u.email},JWT_SECRET,{expiresIn:'7d'});}
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next();}catch{return res.status(401).json({error:'Invalid or expired token'});}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Admin access required'});next();}
function publicUser(id){return db.prepare('SELECT id,full_name,email,phone,city,role,membership_plan,created_at,updated_at FROM users WHERE id=?').get(id);}
function safeUser(u){return u?{id:u.id,name:u.full_name,email:u.email,phone:u.phone,city:u.city,role:u.role,membershipPlan:u.membership_plan,createdAt:u.created_at}:null;}
function seed(){
 const count=db.prepare('SELECT COUNT(*) c FROM vehicles').get().c;
 if(!count){const rows=[
 ['seal','BYD SEAL','Electric Sedan','Sedan','₦35,000,000','650 km','82.5 kWh','3.8 s','Executive Sedan','A dynamic and intelligent all-electric executive sedan built around performance, efficiency and advanced technology.'],
 ['atto3','BYD ATTO 3','Electric SUV','SUV','₦28,500,000','480 km','60.5 kWh','7.3 s','Compact SUV','Expressive, refined and practical electric SUV with a comfortable cabin and smart technology.'],
 ['han','BYD HAN','Electric Sedan','Sedan','₦42,000,000','521 km','85.4 kWh','3.9 s','Premium Sedan','A premium electric sedan combining elegant design, all-wheel drive and high-performance acceleration.'],
 ['dolphin','BYD DOLPHIN','Electric Hatchback','Hatchback','₦23,500,000','427 km','60.4 kWh','7.0 s','City Hatchback','Agile and versatile electric hatchback designed for everyday urban driving.'],
 ['tang','BYD TANG','Electric SUV','SUV','₦38,000,000','530 km','108.8 kWh','4.9 s','7-Seater SUV','A spacious seven-seat performance SUV with all-wheel drive and family-focused comfort.'],
 ['seal-u','BYD SEAL U DM-i','Hybrid SUV','SUV','₦33,000,000','1,100+ km','18.3 kWh','8.5 s','Super Hybrid','A practical family SUV combining electric driving with long-distance flexibility.']];
 const st=db.prepare('INSERT INTO vehicles(slug,name,type,category,price,range_km,battery,acceleration,tag,description) VALUES (?,?,?,?,?,?,?,?,?,?)'); const tx=db.transaction(()=>rows.forEach(r=>st.run(...r)));tx();}
 const mc=db.prepare('SELECT COUNT(*) c FROM memberships').get().c;if(!mc){const st=db.prepare('INSERT INTO memberships(name,price,features_json) VALUES (?,?,?)');[['Bronze','Free',['Basic Support','Service Reminders','Member Discounts','Company Updates']],['Silver','₦60,000 / year',['Everything in Bronze','Regular Diagnostics','Priority Health Check','Preventive Maintenance']],['Gold','₦120,000 / year',['Everything in Silver','Special Issue Coverage','Repair Support','Priority Service']],['Platinum','₦200,000 / year',['Everything in Gold','All Repairs Coverage','Full Maintenance Coverage','Priority Booking','24/7 Roadside Assistance']]].forEach(x=>st.run(x[0],x[1],JSON.stringify(x[2])));}
 const adminEmail=email(process.env.ADMIN_EMAIL||'admin@bydev.demo'); if(!db.prepare('SELECT 1 FROM users WHERE email=?').get(adminEmail)){const hash=bcrypt.hashSync(process.env.ADMIN_PASSWORD||'ChangeMe_123!',12);db.prepare('INSERT INTO users(full_name,email,password_hash,role,membership_plan) VALUES (?,?,?,?,?)').run('BYD Administrator',adminEmail,hash,'admin','Platinum');}
}
seed();
app.get('/api/health',(req,res)=>res.json({ok:true,service:'BYD EV API',time:new Date().toISOString()}));
app.post('/api/auth/register',(req,res)=>{const name=clean(req.body.name), e=email(req.body.email), pass=String(req.body.password||'');if(name.length<2||!/^\S+@\S+\.\S+$/.test(e)||pass.length<8)return res.status(400).json({error:'Name, valid email and password of at least 8 characters are required'});if(db.prepare('SELECT id FROM users WHERE email=?').get(e))return res.status(409).json({error:'Email already registered'});const hash=bcrypt.hashSync(pass,12);const info=db.prepare('INSERT INTO users(full_name,email,password_hash,phone,city) VALUES (?,?,?,?,?)').run(name,e,hash,clean(req.body.phone),clean(req.body.city));const u=publicUser(info.lastInsertRowid);res.status(201).json({token:tokenFor(u),user:safeUser(u)});});
app.post('/api/auth/login',(req,res)=>{const e=email(req.body.email),pass=String(req.body.password||'');const u=db.prepare('SELECT * FROM users WHERE email=?').get(e);if(!u||!bcrypt.compareSync(pass,u.password_hash))return res.status(401).json({error:'Invalid email or password'});res.json({token:tokenFor(u),user:safeUser(u)});});
app.get('/api/auth/me',auth,(req,res)=>{const u=publicUser(req.user.sub);if(!u)return res.status(404).json({error:'User not found'});res.json({user:safeUser(u)});});
app.get('/api/vehicles',(req,res)=>{const {category,active='1'}=req.query;let q='SELECT * FROM vehicles WHERE 1=1',p=[];if(active!=='all'){q+=' AND active=?';p.push(Number(active)?1:0)}if(category&&category!=='all'){q+=' AND (category=? OR type LIKE ?)';p.push(category,`%${category}%`)}q+=' ORDER BY id';res.json({vehicles:db.prepare(q).all(...p)});});
app.get('/api/vehicles/:slug',(req,res)=>{const v=db.prepare('SELECT * FROM vehicles WHERE slug=?').get(req.params.slug);if(!v)return res.status(404).json({error:'Vehicle not found'});res.json({vehicle:v});});
app.get('/api/memberships',(req,res)=>res.json({memberships:db.prepare('SELECT * FROM memberships WHERE active=1 ORDER BY id').all().map(x=>({...x,features:JSON.parse(x.features_json)}))}));
app.put('/api/profile',auth,(req,res)=>{const name=clean(req.body.name),phone=clean(req.body.phone),city=clean(req.body.city);if(name.length<2)return res.status(400).json({error:'Name is required'});db.prepare('UPDATE users SET full_name=?,phone=?,city=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(name,phone,city,req.user.sub);res.json({user:safeUser(publicUser(req.user.sub))});});
app.post('/api/membership/select',auth,(req,res)=>{const plan=clean(req.body.plan);if(!db.prepare('SELECT id FROM memberships WHERE name=? AND active=1').get(plan))return res.status(400).json({error:'Invalid membership plan'});db.prepare('UPDATE users SET membership_plan=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(plan,req.user.sub);res.json({message:`${plan} membership selected`,user:safeUser(publicUser(req.user.sub))});});
app.get('/api/my/vehicles',auth,(req,res)=>res.json({vehicles:db.prepare('SELECT uv.*,v.name,v.slug,v.type,v.price,v.range_km,v.battery,v.acceleration FROM user_vehicles uv JOIN vehicles v ON v.id=uv.vehicle_id WHERE uv.user_id=? ORDER BY uv.id DESC').all(req.user.sub)}));
app.post('/api/my/vehicles',auth,(req,res)=>{const v=db.prepare('SELECT id FROM vehicles WHERE slug=?').get(clean(req.body.slug));const vin=clean(req.body.vin);if(!v||!vin)return res.status(400).json({error:'Valid vehicle and VIN are required'});try{const info=db.prepare('INSERT INTO user_vehicles(user_id,vehicle_id,vin,color,purchase_date) VALUES (?,?,?,?,?)').run(req.user.sub,v.id,vin,clean(req.body.color),clean(req.body.purchaseDate));res.status(201).json({vehicle:db.prepare('SELECT uv.*,v.name,v.slug FROM user_vehicles uv JOIN vehicles v ON v.id=uv.vehicle_id WHERE uv.id=?').get(info.lastInsertRowid)});}catch(e){res.status(409).json({error:'VIN already registered'});}});
app.get('/api/appointments',auth,(req,res)=>res.json({appointments:db.prepare('SELECT a.*,v.name vehicle_name FROM appointments a LEFT JOIN vehicles v ON v.id=a.vehicle_id WHERE a.user_id=? ORDER BY appointment_date DESC,appointment_time DESC').all(req.user.sub)}));
app.post('/api/appointments',auth,(req,res)=>{const service=clean(req.body.service),date=clean(req.body.date),time=clean(req.body.time);if(!service||!date||!time)return res.status(400).json({error:'Service, date and time are required'});const info=db.prepare('INSERT INTO appointments(user_id,vehicle_id,service,appointment_date,appointment_time,location,notes) VALUES (?,?,?,?,?,?,?)').run(req.user.sub,Number(req.body.vehicleId)||null,service,date,time,clean(req.body.location)||'BYD Service Centre',clean(req.body.notes));res.status(201).json({appointment:db.prepare('SELECT * FROM appointments WHERE id=?').get(info.lastInsertRowid)});});
app.post('/api/test-drives',auth,(req,res)=>{const model=clean(req.body.model),name=clean(req.body.fullName),phone=clean(req.body.phone),date=clean(req.body.date),time=clean(req.body.time);if(!model||!name||!phone||!date||!time)return res.status(400).json({error:'All test-drive fields are required'});const info=db.prepare('INSERT INTO test_drives(user_id,model,full_name,phone,drive_date,drive_time) VALUES (?,?,?,?,?,?)').run(req.user.sub,model,name,phone,date,time);res.status(201).json({testDrive:db.prepare('SELECT * FROM test_drives WHERE id=?').get(info.lastInsertRowid)});});
app.post('/api/quotes',auth,(req,res)=>{const model=clean(req.body.model),name=clean(req.body.fullName),e=email(req.body.email),msg=clean(req.body.message);if(!model||!name||!e)return res.status(400).json({error:'Model, name and email are required'});const info=db.prepare('INSERT INTO quotes(user_id,model,full_name,email,message) VALUES (?,?,?,?,?)').run(req.user.sub,model,name,e,msg);res.status(201).json({quote:db.prepare('SELECT * FROM quotes WHERE id=?').get(info.lastInsertRowid)});});
app.post('/api/contact',(req,res)=>{const name=clean(req.body.name),e=email(req.body.email),msg=clean(req.body.message);if(!name||!e||!msg)return res.status(400).json({error:'Name, email and message are required'});const info=db.prepare('INSERT INTO contacts(name,email,message) VALUES (?,?,?)').run(name,e,msg);res.status(201).json({message:'Enquiry received',id:info.lastInsertRowid});});
app.get('/api/support',auth,(req,res)=>res.json({tickets:db.prepare('SELECT * FROM support_tickets WHERE user_id=? ORDER BY id DESC').all(req.user.sub)}));
app.post('/api/support',auth,(req,res)=>{const subject=clean(req.body.subject)||'General Support',message=clean(req.body.message);if(!message)return res.status(400).json({error:'Message is required'});const info=db.prepare('INSERT INTO support_tickets(user_id,subject,message,priority) VALUES (?,?,?,?)').run(req.user.sub,subject,message,clean(req.body.priority)||'Normal');res.status(201).json({ticket:db.prepare('SELECT * FROM support_tickets WHERE id=?').get(info.lastInsertRowid)});});
app.get('/api/service-history',auth,(req,res)=>res.json({history:db.prepare('SELECT sh.*,v.name vehicle_name FROM service_history sh LEFT JOIN vehicles v ON v.id=sh.vehicle_id WHERE sh.user_id=? ORDER BY service_date DESC').all(req.user.sub)}));
app.get('/api/payments',auth,(req,res)=>res.json({payments:db.prepare('SELECT id,amount,currency,description,status,reference,created_at FROM payments WHERE user_id=? ORDER BY id DESC').all(req.user.sub)}));
app.get('/api/dashboard',auth,(req,res)=>{const u=publicUser(req.user.sub);res.json({user:safeUser(u),vehicle:db.prepare('SELECT uv.*,v.name,v.type,v.slug,v.range_km,v.battery,v.acceleration FROM user_vehicles uv JOIN vehicles v ON v.id=uv.vehicle_id WHERE uv.user_id=? ORDER BY uv.id DESC LIMIT 1').get(req.user.sub)||null,appointments:db.prepare('SELECT a.*,v.name vehicle_name FROM appointments a LEFT JOIN vehicles v ON v.id=a.vehicle_id WHERE a.user_id=? AND a.status NOT IN (\'Cancelled\',\'Completed\') ORDER BY appointment_date,appointment_time LIMIT 3').all(req.user.sub),serviceCount:db.prepare('SELECT COUNT(*) c FROM service_history WHERE user_id=?').get(req.user.sub).c});});
// Admin API
app.get('/api/admin/stats',auth,admin,(req,res)=>{const c=t=>db.prepare(`SELECT COUNT(*) c FROM ${t}`).get().c;res.json({users:c('users'),vehicles:c('vehicles'),appointments:c('appointments'),testDrives:c('test_drives'),quotes:c('quotes'),contacts:c('contacts'),tickets:c('support_tickets')});});
app.get('/api/admin/users',auth,admin,(req,res)=>res.json({users:db.prepare('SELECT id,full_name,email,phone,city,role,membership_plan,created_at FROM users ORDER BY id DESC').all()}));
app.get('/api/admin/appointments',auth,admin,(req,res)=>res.json({appointments:db.prepare('SELECT a.*,u.full_name,u.email,v.name vehicle_name FROM appointments a JOIN users u ON u.id=a.user_id LEFT JOIN vehicles v ON v.id=a.vehicle_id ORDER BY a.id DESC').all()}));
app.patch('/api/admin/appointments/:id',auth,admin,(req,res)=>{const status=clean(req.body.status);if(!['Pending','Confirmed','Completed','Cancelled'].includes(status))return res.status(400).json({error:'Invalid status'});db.prepare('UPDATE appointments SET status=? WHERE id=?').run(status,req.params.id);res.json({appointment:db.prepare('SELECT * FROM appointments WHERE id=?').get(req.params.id)});});
app.get('/api/admin/leads',auth,admin,(req,res)=>res.json({testDrives:db.prepare('SELECT td.*,u.email user_email FROM test_drives td LEFT JOIN users u ON u.id=td.user_id ORDER BY td.id DESC').all(),quotes:db.prepare('SELECT q.*,u.email user_email FROM quotes q LEFT JOIN users u ON u.id=q.user_id ORDER BY q.id DESC').all(),contacts:db.prepare('SELECT * FROM contacts ORDER BY id DESC').all(),tickets:db.prepare('SELECT s.*,u.full_name,u.email FROM support_tickets s LEFT JOIN users u ON u.id=s.user_id ORDER BY s.id DESC').all()}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Internal server error'});});
app.listen(PORT,()=>console.log(`BYD EV API running on http://localhost:${PORT}`));
